config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations"}
  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end  
  get 'users/soft_delete' => 'users/soft_delete'
  root 'users#index'

  resource :user, only: [:edit] do
    collection do
      get 'edit_password'
      patch 'update_password'
    end
  end 

  resources :users do
    resources :employees do
      collection do

        get "dashboard"
        get "send_email" 
        get    'employee_dashboard'
        get    'academic_detail_new'
        post   'academic_detail_create'
        get    'academic_detail_edit'
        patch  'academic_detail_update'
        get    'academic_detail_display'
        get    'basic_detail_new'
        post  'basic_detail_create'
        get    'basic_detail_show'
        get    'basic_detail_edit'
        patch  'basic_detail_update'
        get    'bank_detail_new'
        post   'bank_detail_create'
        get    'bank_detail_show'
        get    'bank_detail_edit'
        patch  'bank_detail_update'
        get    'previous_company_detail_new'
        get    'previous_company_detail_show'
        post   'previous_company_detail_create'
        get    'previous_company_detail_edit'
        patch  'previous_company_detail_update'
        get    'project_new'
        post   'project_create'
        get    'project_show'
        get    'project_edit'
        patch  'project_update'
       end

      end

      resources :sales_consultants do
        collection do
        get    'saleconsultant_new'
        post   'saleconsultant_create'
        get    'saleconsultant_edit'
        get    'saleconsultant_show'
        patch  'saleconsultant_update'
        get    'sales_bd_new'
        post   'sales_bd_create'
        get    'sales_bd_edit'
        get     'sales_bd_show'
        patch  'sales_bd_update'

      end
    end    
  end 
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	def dashboard
	end

	def index
	@employees =EmployeeDetail.all
	end

  def basic_detail_new
	 @employee = current_user.build_employee_detail
  end

	def basic_detail_create   
    @employee = current_user.build_employee_detail(employee_params)
     if @employee.save
      redirect_to  basic_detail_show_user_employees_path(current_user, @employee), :notice => "Details are succesfully saved."
     else
      render 'basic_detail_new'
     end
  end

  def basic_detail_show
    if current_user.employee_detail.blank?
      redirect_to  basic_detail_new_user_employees_path(current_user)   
    else
      @employee = current_user.employee_detail
    end
  end

	def basic_detail_edit
    @employee = current_user.employee_detail
  end

  def basic_detail_update
    @employee = current_user.employee_detail
      if @employee.update_attributes(employee_params)
        redirect_to basic_detail_show_user_employees_path,:notice => "Your Details are  updated"
      else
        render 'basic_detail_edit_user_employees'
      end
  end

  def academic_detail_new
   @academic = current_user.academic_details.new
  end

	def academic_detail_display
	 if current_user.academic_details.blank?
	  redirect_to academic_detail_new_user_employees_path(current_user)
	 else
	  @academices = current_user.academic_details
	 end 
	end

	def academic_detail_edit
	 @academic = current_user.academic_details.find(params[:academic])
	end

	def academic_detail_create
	 @academic = current_user.academic_details.create(academic_params)
	 if @academic.save
	  redirect_to academic_detail_display_user_employees_path(current_user), :notice => "Details are saved."
	 else
		render "academic_detail_new"
	 end
	end

	def academic_detail_update
	 @academic = current_user.academic_details.find(params[:academic])
	 if @academic.update_attributes(academic_params)
		redirect_to academic_detail_display_user_employees_path(current_user)
	 else
		render 'academic_detail_edit'
	 end
  end

  def bank_detail_new
    @bank = current_user.build_bank_and_identity_detail
  end

  def bank_detail_show
    if current_user.bank_and_identity_detail.blank?
      redirect_to bank_detail_new_user_employees_path(current_user)
    else
      @bank = current_user.bank_and_identity_detail
    end
  end

  def bank_detail_edit
    @bank = current_user.bank_and_identity_detail
  end
  
  def bank_detail_create
    @bank = current_user.build_bank_and_identity_detail(bank_and_identity_params)
    if @bank.save
      redirect_to bank_detail_show_user_employees_path(current_user), :notice => "your banking Details saved."
    else
      render "bank_detail_new"
    end
  end

  def bank_detail_update
    @bank = current_user.bank_and_identity_detail
    if @bank.update_attributes(bank_and_identity_params)
      redirect_to bank_detail_show_user_employees_path(current_user)
    else
      render 'bank_detail_edit'
    end
  end

  def previous_company_detail_new
    @previous = current_user.pre_company_details.new
  end
  
  def previous_company_detail_show
    if current_user.pre_company_details.blank?
      redirect_to previous_company_detail_new_user_employees_path(current_user)
    else
      @previous = current_user.pre_company_details
    end
  end

  def previous_company_detail_create
    @previous =  current_user.pre_company_details.create(previous_params)
    if @previous.save
      redirect_to previous_company_detail_show_user_employees_path, :notice => "Details saved."
    else
      render 'previous_company_detail_new'
    end
  end

  def previous_company_detail_edit
  
    @previous = current_user.pre_company_details.find(params[:pre])
  end

  def previous_company_detail_update
    @previous = current_user.pre_company_details.find(params[:pre])
    if @previous.update_attributes(previous_params)
      redirect_to previous_company_detail_show_user_employees_path(current_user)
    else
      render 'previous_company_detail_edit'
    end
  end
  
  def project_new
    @project =  current_user.project_details.new 
  end

  def project_edit
    @project =  current_user.project_details.find(params[:projectdetail])
  end

  def project_create
    @project =  current_user.project_details.create(project_params)
    if @project.save
      redirect_to project_show_user_employees_path, :notice => "your Details are saved."
    else
      render 'project_new'
    end
  end
 
  def project_update
    @project =  current_user.project_details.find(params[:projectdetail])
    if @project.update_attributes(project_params)
      redirect_to project_show_user_employees_path(current_user)
    else
      render 'project_edit'
    end
  end
 
  def project_show
    if current_user.project_details.blank?
      redirect_to project_new_user_employees_path(current_user)
    else
      @projects = current_user.project_details
    end
  end

  def send_email
    user = User.find(params[:user_id])
    UserMailer.welcome(user).deliver_now
    UserMailer.new_user_account(user).deliver_now
    respond_to do |format|
      format.js
    end
  end 

	private

	def academic_params
    params.require(:academic_detail).permit(:user_id, :course, :university, :passing_year, :percentage, :stream)
  end

  def bank_and_identity_params
      params.require(:bank_and_identity_detail).permit(:user_id,:account_no,:bank_name,:branch_name,:city,:ifsc_code,:pancard_no,:passport_no,:uid_no)
  end

	def employee_params
	 params.require(:employee_detail).permit(:user_id,:personal_email_id,:firstname,:lastname,:dob,:date_of_join,:blood_group,:official_email_id,:mobile,:landline,:current_address,:permanent_address,:skype_id,:guardian_full_name,:guardian_mobile,:guardian_landline,:guardian_address)
	end

	def previous_params
      params.require(:pre_company_detail).permit(:user_id, :company_name, :location, :designation, :from, :to, :last_CTC, :Resignation_reason,:employee_id )
  end

  def project_params
  	 params.require(:project_detail).permit(:user_id, :project_name,:your_role,:project_url,:description, :technology, :client_name,:company_name,:duration, :team_lead_name)
  end


	end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/academic_detail_display.html.erb
<section id="main-content">
  <section class="wrapper">
    <div class="row">
     <div class="col-lg-12">
      <section class="panel">
        <header class="panel-heading"><h4>Your Academic Details</h4>
         <span class="pull-right button"><%= link_to "Add More", academic_detail_new_user_employees_path(current_user), class: "btn btn-shadow btn-info btn-sm" %>
         </span>
        </header>

        <table class="table table-bordered table-striped table-condensed">
          <thead>
            <tr>
              <th>Course Name</th>
              <th>University/Board Name</th>
              <th>Stream</th>
              <th>Passing Year</th>
              <th>Percentage</th>
            </tr>
          </thead>
          <tbody>
            <% @academices.each do |academic| %>
              <tr>
                <td><%= academic.course %></td>
                <td><%= academic.university%></td>
                <td><%= academic.stream %></td>
                <td><%= academic.passing_year.strftime("%Y") %></td>
                <td><%= academic.percentage %></td>
                <td><%= link_to "Edit",  academic_detail_edit_user_employees_path(current_user, :academic => academic),class: "btn btn-shadow btn-info btn-xs" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </section>
     </div>
    </div>
   </section>
  </section>
</section>

app/views/employees/academic_detail_edit.html.erb
<section id="main-content">
 <section class="wrapper">
  <section class="panel">
   <div class="col-lg-12">
    <section class="panel padding">
     <header class="panel-heading"><h4>Edit Your Details</h4></header>
      <%= form_for @academic, :url => academic_detail_update_user_employees_path(current_user, :academic => @academic.id) do |f| %>
        <div class=" col-lg-2"></div>
         <div class="panel-body">
          <div class="form">
           <% if @academic.errors.any? %>
            <div id="error_explanation" class ="alert alert-danger">
             <ul>
              <% @academic.errors.full_messages.each do |message| %>
               <li><%= message %></li>
              <% end %>
             </ul>
            </div>
           <% end %>
           <div class=" form col-lg-12">
            <form class="cmxform form-horizontal tasi-form" id="commentForm" method="get" action="">
              <div class="form-group ">
                <label class="col-lg-2 control-label"> Course Name* </label>
                <div class="col-lg-10">
                  <%= f.text_field :course, :class=>"form-control", :id => "text-transform",:required => true %><br />
                </div>
              </div>
              <div class="form-group ">
                <label class="col-lg-2 control-label"> University/Board* </label>
                <div class="col-lg-10">
                  <%= f.text_field :university, :id => "text-transform", :class=>"form-control", :required => true %><br />
                </div>
              </div>
              <div class="form-group ">
                <label class="col-lg-2 control-label"> Year Of Passing*</label>
                <div class="col-lg-10">
                  <%= f.date_select :passing_year ,{order: [:year], prompt: {  year: 'Select year' }, start_year: Date.today.year - 0, end_year: Date.today.year - 100} , {required: true}%>
                  <br /><br />
                </div>
              </div>
              <div class="form-group ">
                <label class="col-lg-2 control-label"> Percentage* </label>
                <div class="col-lg-10">
                  <%= f.text_field :percentage,  :class=>"form-control", :required => true  %><br />
                </div>
              </div>
              <div class="form-group ">
                <label class="col-lg-2 control-label"> Stream* </label>
                <div class="col-lg-10">
                  <%= f.text_field :stream,  :class=>"form-control", :required => true  %><br />
                </div>
              </div>
              <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                  <center>
                    <button class="btn btn-shadow btn-danger" type="submit">Update</button>
                  </center>
                </div>
            </div>
          </form>
        </div>
      </div>
      <% end %>
    </div>
    </section>
  </section>
</section>

app/views/employees/academic_detail_new.html.erb
z<section id="main-content">
 <section class="wrapper">
  <section class="panel">
   <div class="col-lg-12">
    <section class="panel padding" >
     <header class="panel-heading"><h4>Fill Your Academic Details</h4></header>
      <%= form_for @academic, :url => academic_detail_create_user_employees_path(current_user) do |f| %>
       <div class=" col-lg-3"></div>
        <div class="panel-body">
         <div class="form">
          <% if @academic.errors.any? %>
            <div id="error_explanation" class ="alert alert-danger">
              <ul>
                <% @academic.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
             </div>
          <% end %>
          <div class=" form col-lg-12">
            <form class="cmxform form-horizontal tasi-form" id="commentForm" method="get" action="">
            <!-- <div class="form-group "> -->
              <div class="form-group ">
                <label class="col-lg-2 control-label"> Course Name* </label>
                <div class="col-lg-10">
                  <%= f.text_field :course, :class=>"form-control", :id => "text-transform",:required => true %><br />
                </div>
              </div>

              <div class="form-group ">
                <label class="col-lg-2 control-label"> Stream* </label>
                  <div class="col-lg-10">
                    <%= f.text_field :stream,  :class=>"form-control", :required => true  %><br />
                  </div>
              </div>

              <div class="form-group ">
                <label class="col-lg-2 control-label"> University/Board* </label>
                  <div class="col-lg-10">
                    <%= f.text_field :university, :id => "text-transform", :class=>"form-control", :required => true %><br />
                  </div>
              </div>

              <div class="form-group ">
                <label class="col-lg-2 control-label"> Year Of Passing*</label>
                  <div class="col-lg-10">
                    <%= f.date_select :passing_year ,{order: [:year], prompt: {  year: 'Select year' }, start_year: Date.today.year+1, end_year: Date.today.year-20} , {required: true}%>
                    <br /><br />
                  </div>
               </div>

              <div class="form-group ">
                <label class="col-lg-2 control-label"> Percentage* </label>
                  <div class="col-lg-10">
                    <%= f.text_field :percentage,  :class=>"form-control", :required => true  %><br />
                  </div>
              </div> 
              <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                  <center><button class="btn btn-shadow btn-danger" type="submit">Save</button>
                    <button class="btn btn-shadow btn-default btn-md" type="reset">Reset</button>
                  </center>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
     <% end %>
    </section>
    </div>
   </section>
  </section>
</section>

app/views/employees/bank_detail_edit.html.erb
<section id="main-content">
 <section class="wrapper">
  <section class="panel">
   <div class="col-lg-12">
     <section class="panel" id="panel-margin">
        <header class="panel-heading">
          <bold><h4>Edit Bank Identity Details</h4></bold>
        </header>
            <%= form_for @bank, :url => bank_detail_update_user_employees_path(current_user,:bankidentity => @bank.id) do |f| %>
            <div class=" col-lg-3">
            </div>
            <div class="panel-body">
            <div class="form">
              <%if @bank.errors.any? %>
              <div id="error_explanation" class ="alert alert-danger">
                <ul>
                  <% @bank.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
              <% end %>
              <div class=" form col-lg-12">
                <form class="cmxform form-horizontal tasi-form" id="commentForm" method="get" action="">
                  <!-- <div class="form-group "> -->
                  <div class="form-group ">
                    <label class="col-lg-2 control-label"> Bank Account No* </label>
                    <div class="col-lg-10">
                      <%= f.text_field :account_no, :class=>"form-control", :required => true %><br />
                    </div>
                  </div>
                  <div class="form-group ">
                    <label class="col-lg-2 control-label"> Bank Name* </label>
                    <div class="col-lg-10">
                      <%= f.text_field :bank_name,  :class=>"form-control", :required => true %><br />
                    </div>
                  </div>
                  <div class="form-group ">
                    <label class="col-lg-2 control-label"> Branch Name* </label>
                    <div class="col-lg-10">
                      <%= f.text_field :branch_name,  :class=>"form-control", :required => true  %><br />
                    </div>
                  </div>
                  <div class="form-group ">
                    <label class="col-lg-2 control-label"> City* </label>
                    <div class="col-lg-10">
                      <%= f.text_field :city, :class=>"form-control" %><br />
                    </div>
                  </div>
                  <div class="form-group ">
                    <label class="col-lg-2 control-label"> IFSC Code* </label>
                    <div class="col-lg-10">
                      <%= f.text_field :ifsc_code,  :class=>"form-control", :required => true  %><br />
                    </div>
                  </div>
                  <div class="form-group ">
                    <label class="col-lg-2 control-label"> Pancard No* </label>
                    <div class="col-lg-10">
                      <%= f.text_field :pancard_no,  :class=>"form-control", :required => true %><br />
                    </div>
                  </div>
                  <div class="form-group ">
                    <label class="col-lg-2 control-label"> Passport No</label>
                    <div class="col-lg-10">
                      <%= f.text_field :passport_no,  :class=>"form-control" %><br />
                    </div>
                  </div>
                  <div class="form-group ">
                    <label class="col-lg-2 control-label"> UID No</label>
                    <div class="col-lg-10">
                      <%= f.text_field :uid_no,  :class=>"form-control" %><br />
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                      <center>
                        <button class="btn btn-shadow btn-danger" type="submit">Update</button>
                      </center>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          <% end %>
        </div>
      </section>
    </div>
 </section>
</section>

app/views/employees/bank_detail_new.html.erb
<section id="main-content">
  <section class="wrapper">
    <section class="panel">
      <div class="col-lg-12">
       <section class="panel" id="panel-margin">
        <header class="panel-heading"><h4>Fill Your Bank Details</h4></header>
        <%= form_for @bank, :url => bank_detail_create_user_employees_path(current_user) do |f| %>
          <div class=" col-lg-3"></div>
           <div class="panel-body">
            <div class="form">
              <%if @bank.errors.any? %>
               <div id="error_explanation" class ="alert alert-danger">
                <ul>
                  <% @bank.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
                 </ul>
               </div>
              <% end %>

              <div class=" form col-lg-12">
                <form class="cmxform form-horizontal tasi-form" id="commentForm" method="get" action="">
                  <!-- <div class="form-group "> -->
                    <div class="form-group ">
                      <label class="col-lg-2 control-label"> Bank Account No* </label>
                      <div class="col-lg-10">
                        <%= f.text_field :account_no, :class =>"form-control", :required => true %><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-2 control-label"> Bank Name* </label>
                      <div class="col-lg-10">
                        <%= f.text_field :bank_name,  :class=>"form-control", :required => true %><br />
                      </div>
                    </div>

                    <div class="form-group ">
                      <label class="col-lg-2 control-label"> Branch Name* </label>
                      <div class="col-lg-10">
                        <%= f.text_field :branch_name,  :class=>"form-control", :required => true  %><br />
                      </div>
                    </div>

                    <div class="form-group ">
                      <label class="col-lg-2 control-label"> City* </label>
                      <div class="col-lg-10">
                        <%= f.text_field :city, :class=>"form-control" %><br />
                      </div>
                    </div>

                    <div class="form-group ">
                      <label class="col-lg-2 control-label"> IFSC Code* </label>
                      <div class="col-lg-10">
                        <%= f.text_field :ifsc_code,  :class=>"form-control", :required => true, :placeholder => "Enter 11 digits"  %><br />
                      </div>
                    </div>
                  </section>
                  
                    <section class = "panel margin_panel">
                      <div class="panel-body">
                        <div class="col-lg-12">
                          <header class="panel-heading bottom"><h4>Fill Your Identity Details</h4></header>
                         <section class="panel" id="panel-margin">   
                         

                          <div class="form-group ">
                            <label class="col-lg-2 control-label"> Pancard No* </label>
                            <div class="col-lg-10">
                              <%= f.text_field :pancard_no,  :class=>"form-control", :required => true, :placeholder => "Example:-VWXYZ1234X" %><br />
                            </div>
                          </div>

                          <div class="form-group ">
                            <label class="col-lg-2 control-label"> Passport No</label>
                            <div class="col-lg-10">
                              <%= f.text_field :passport_no,  :class=>"form-control" %><br />
                            </div>
                          </div>

                          <div class="form-group ">
                            <label class="col-lg-2 control-label"> UID No(Adhar card)</label>
                            <div class="col-lg-10">
                              <%= f.text_field :uid_no,  :class=>"form-control", :placeholder =>"enter 12 characters"%><br />
                            </div>
                          </div>
                       
                        <div class="form-group">
                          <div class="col-lg-offset-2 col-lg-10">
                            <center><button class="btn btn-shadow btn-danger" type="submit">Save</button>
                              <button class="btn btn-shadow btn-default btn-md" type="reset">Reset</button>
                            </center>
                          </div>
                        </div>
                      </div>
                    </div>
                  </section>
                </form>
              </div>

            </div>
          <% end %>
        </div>
  </section>
</section>

app/views/employees/bank_detail_show.html.erb
<section id="main-content">
 <section class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <section class="panel">
        <header class="panel-heading"> Your Bank Identity Details
          </header>

         <table class="table table-bordered table-striped table-condensed">
            <thead>
              <tr>
                <th>Bank Account No</th>
                <th>Bank Name</th>
                <th>Branch Name</th>
                <th>City</th>
                <th>IFSC Code</th>
                <th>Pancard No</th>
                <th>Passport No</th>
                <th>UID No</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
                <tr>
                  <td><%= @bank.account_no %></td>
                  <td><%= @bank.bank_name%></td>
                  <td><%= @bank.branch_name.titleize%></td>
                  <td><%= @bank.city.titleize %></td>
                  <td><%= @bank.ifsc_code%></td>
                  <td><%= @bank.pancard_no%></td>
                  <td><%= @bank.passport_no %></td>
                  <td><%= @bank.uid_no%></td>
                  <td><%= link_to "Edit",  bank_detail_edit_user_employees_path(current_user,:bankidentity => @bank),class: "btn btn-shadow btn-info btn-xs" %></td>
                </tr>
           
             </tbody>
          </table>
       </section>
    
      </div>
    </div>
  </section>
</section>
</section>

app/views/employees/basic_detail_show.html.erb
]<section id="main-content">
  <section class="wrapper">
    <div class="row">
      <div class="col-lg-12">
        <section class="panel">
          <header class="panel-heading"><h4>Your Details</h4></header>
          <table class="table table-striped table-condensed">
            <tr>
              <strong>
                <th colspan="2" class="list-group-item-info"><b>BASIC DETAILS</b></th>
              </strong>
            <tr>
             <th>Profile Picture</th>
            </tr>

            <tr>
              <th>First Name</th>
                <td><%= @employee.firstname.titleize %></td>
            </tr>

            <tr>
              <th>Last Name </th>
              <td><%= @employee.lastname.titleize %></td>
            </tr>

            <tr>
              <th>Date Of Birth </th>
              <td><%= @employee.dob %></td>
            </tr>

            <tr>
              <th>Date Of Joining</th>
              <td><%= @employee.date_of_join %></td>
            </tr>

            <tr>
              <th>Blood Group</th>
              <td><%= @employee.blood_group %></td>
            </tr>
            
           
            </section>

            <section class="panel">
            <tr>
              <strong>
                <th colspan="2" class="list-group-item-info">CONTACT DETAILS</th>
              </strong>
            </tr>
            <tr>
              <th>Personal Email Id</th>
              <td><%= @employee.personal_email_id %></td>
            </tr>
            <tr>
              <th>Official Email Id</th>
              <td><%= @employee.official_email_id %></td>
            </tr>
            <tr>
              <th>Skype Id</th>
              <td><%= @employee.skype_id %></td>
            </tr>
            <tr>
              <th>Mobile No</th>
              <td><%= @employee.mobile %></td>
            </tr>
            <tr>
              <th>Landline No</th>
              <td><%= @employee.landline %></td>
            </tr>
            <tr>
              <th>Current Address</th>
              <td><%= @employee.current_address %></td>
            </tr>
            <tr>
              <th>Permanent Address</th>
              <td><%= @employee.permanent_address %></td>
            </tr>
            </section>

            <section class="panel">
                <strong>
                  <th colspan="2" class="list-group-item-info ">PARENTS & GAURDIAN DETAILS</th>
                </strong>
            <tr>
            <th>Guardian Full Name </th>
            <td><%= @employee.guardian_full_name.titleize %></td>
            </tr>
            <tr>
              <th>Guardian Mobile No</th>
              <td><%= @employee.guardian_mobile %></td>
            </tr>
            <tr>
              <th>Guardian Landline No</th>
              <td><%= @employee.guardian_landline %></td>
            </tr>
            <tr>
              <th>Guardian Address</th>
              <td><%= @employee.guardian_address %></td>
            </tr>
            </section>
          </table>
          <h4 class="heading4"><%= link_to "Edit",basic_detail_edit_user_employees_path(current_user,@employee) ,class: "btn btn-shadow btn-info btn-xs"%></h4>
          <br/>
      </div>
    </div>
  </section>
</section>

app/views/employees/dashboard.html.erb
Welcome tour are on the users dashboard

app/views/employees/previous_company_detail_show.html.erb
<section id="main-content">
 <section class="wrapper">
  <div class="row">
   <div class="col-lg-12">
    <section class="panel">
     <header class="panel-heading">Ex-employer Details
        <span class="pull-right"><%= link_to "Add More",  previous_company_detail_new_user_employees_path(current_user),class: "btn btn-shadow btn-info btn-sm" %>
        </span>
     </header>
      <table class="table table-bordered table-striped table-condensed">
        <thead>
          <tr>
            <th>Employee ID</th>
            <th>Company Name</th>
            <th>Location</th>
            <th>Designation</th>
            <th>From Year</th>
            <th>To Year</th>
            <th>Last Salary</th>
            <th>Reason For Resign</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @previous.each do |pre| %>
            <% if current_user.id == pre.user_id %>
            <tr>
              <td><%= pre.employee_id %></td>
              <td><%= pre.company_name %></td>
              <td><%= pre.location.titleize %></td>
              <td><%= pre.designation %></td>
              <td><%= pre.from %></td>
              <td><%= pre.to %></td>
              <td><%= pre.last_CTC %></td>
              <td><%= pre.Resignation_reason %></td>
              <td><%= link_to "Edit",  previous_company_detail_edit_user_employees_path(current_user, :pre => pre),class: "btn btn-shadow btn-info btn-xs" %></td>
            </tr>
              <%end%>
            <%end%>
          </tbody>
        </table>
      </section>
       </div>
    </div>
  </section>
</section>
</section>