config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations"}
  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end  
  get 'users/soft_delete' => 'users/soft_delete'
  root 'users#index'

  resource :user, only: [:edit] do
    collection do
      get 'edit_password'
      patch 'update_password'
    end
  end 

  resources :users do
    resources :employees do
      collection do

        get "dashboard"
        get "send_email" 
        get    'employee_dashboard'
        get    'academic_detail_new'
        post   'academic_detail_create'
        get    'academic_detail_edit'
        patch  'academic_detail_update'
        get    'academic_detail_display'
        get    'basic_detail_new'
        post  'basic_detail_create'
        get    'basic_detail_show'
        get    'basic_detail_edit'
        patch  'basic_detail_update'
        get    'bank_detail_new'
        post   'bank_detail_create'
        get    'bank_detail_show'
        get    'bank_detail_edit'
        patch  'bank_detail_update'
        get    'previous_company_detail_new'
        get    'previous_company_detail_show'
        post   'previous_company_detail_create'
        get    'previous_company_detail_edit'
        patch  'previous_company_detail_update'
        get    'project_new'
        post   'project_create'
        get    'project_show'
        get    'project_edit'
        patch  'project_update'
       end

      end

      resources :sales_consultants do
        collection do
        get    'saleconsultant_new'
        post   'saleconsultant_create'
        get    'saleconsultant_edit'
        get    'saleconsultant_show'
        patch  'saleconsultant_update'
        get    'sales_bd_new'
        post   'sales_bd_create'
        get    'sales_bd_edit'
        get     'sales_bd_show'
        patch  'sales_bd_update'

      end
    end    
  end 
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise        :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable
	belongs_to    :role
	before_create :prepare_username,:gen_password
	after_create  :send_mail
 
  has_one :employee_detail
  extend FriendlyId
  friendly_id :username, use: :slugged
  devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
  has_one  :employee_detail
  has_one  :bank_and_identity_detail
  has_many :academic_details 
  has_many :pre_company_details
  has_many :project_details
  has_many :sales_consultants
  has_many :sales_bds
  belongs_to :role
  before_create :prepare_username,:gen_password
  after_create :send_mail
	before_save { self.email = email.downcase}
	validates :firstname,:lastname ,presence:true
	# validates :firstname,:lastname,format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }

	validates_confirmation_of :password 
	VALID_EMAIL_REGEX =/\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  
	def prepare_username
		self.username = (self.firstname[0..2] +"."+self.lastname).to_s.downcase
	end

	def password_required?
	 false
	end

	def email_required?
	 true
	end

	def gen_password
	 rand_password =  [('a'..'z'), (0..9)].map{|i| i.to_a}.flatten
	 self.password = self.password_confirmation = self.pwd = (0..5).map{ rand_password[rand(rand_password.length)] }.join if self.password.blank?
	end
	
	def send_mail 
		UserMailer.welcome(self).deliver_now
		UserMailer.new_user_account(self).deliver_now
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user , only:[:edit_password,:update_password]

 def index
	@user = current_user
	@users = User.where(:soft_delete => false).order(:created_at => :DESC)
 end

	def show
		@user = User.friendly.find(params[:id])
	end

	def new
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to user_url, notice: "Updated User."
		else
			render :edit
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
		  redirect_to user_url, notice: "User succesfully created!" 
		else
		  render :new
	  end
	end


	def show
	 @user = User.friendly.find(params[:id])
	end


	def edit_password
	end

	def update_password
	if @user.update(update_user_params)
	  redirect_to root_path,:notice => "Password Has been Changed Successfully..!"
	else
	  render "edit_password"
	end
	end

	def soft_delete
	 @user = User.find(params[:id])
	 @user.update_attribute(:soft_delete,1)
	 redirect_to users_path
	end

	 private
	def set_user
  	@user = User.find(params[:id])
	end

	def user_params
	 params.require(:user).permit(:role,:soft_delete)
	end

	def update_user_params
	 params.require(:user).permit(:password, :password_confirmation)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit_password.html.erb
<section id="main-content">
  <section class="panel">
    <div class="col-lg-12">
   <section class="panel" style= padding-top:5px;>
    <header class="panel-heading">
      <bold>
        <h4>Change Password</h4>
      </bold>
    </header>
    <%= form_for(@user, :url => update_password_user_path(current_user,:id=>@user.id)) do |f| %>
      <div class=" col-lg-12">
        </div>
         <div class="panel-body">
           <div class="form">
             <% if @user.errors.any? %>
               <div id="error_explanation" class ="alert alert-danger">
                 <ul>
                  <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                 </ul>
               </div>
             <%end%>
                <div class=" col-lg-3">
                </div>
                <div class="panel-body">
                  <div class="form">
                    <div class=" form col-lg-9">
                      <form class="cmxform form-horizontal tasi-form" id="commentForm" method="get" action="" autocomplete="off">
                        <div class="form-group ">
                          <label class="col-lg-3 control-label"> New Password </label>
                          <div class="col-lg-8">
                            <%= f.password_field :password, :autocomplete => "off", :style => "width: 205px;"  %><br /><br />
                          </div> 
                        </div>
                        <div class="form-group ">
                          <label class="col-lg-3 control-label"> Confirm Password </label>
                          <div class="col-lg-8">
                            <%= f.password_field :password_confirmation,:autocomplete => "off", :style => "width: 205px;" %><br /><br/>
                          </div>
                        </div>
                        
                    <div class="form-group">
                  <div class="col-lg-offset-3 col-lg-8">
                  <button class="btn btn-shadow btn-warning" type="back">Back</button>
                  <button class="btn btn-shadow btn-danger" type="submit">Change Password</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      <%end%>
    </div>
  </section>
</section>

app/views/users/index.html.erb
<section id="main-content">
	<section class="wrapper">
		<% if current_user.has_role? "admin" %>
		  <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email Id</th>
        </tr>
      </thead>
      <tbody>
		  <% @users.each do |user| %>
        <tr>
          <td><%= user.firstname %></td>
          <td><%= user.lastname%></td>
          <td><%= user.email %></td>
          <td>
            <%= link_to 'Send Email',send_email_user_employees_path(user.id), class: "btn btn-shadow btn-info btn-xs" %>
          </td>
          <td>
            <%= link_to "Remove",users_soft_delete_path(current_user,:id=>user.id),data: { confirm: 'Do You Want to with Continue Delete Process ?' }, class: "btn btn-shadow btn-info btn-xs"%>
          </td>
          <td>
            <%= link_to 'Change Password', edit_password_user_path(current_user, :id=>user.id), class: "btn btn-shadow btn-info btn-xs" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%else%>
      <%= render :template => 'employees/dashboard' %>
		<% end %>
	</section>
</section>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>