config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations"}
  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end  
  get 'users/soft_delete' => 'users/soft_delete'
  root 'users#index'

  resource :user, only: [:edit] do
    collection do
      get 'edit_password'
      patch 'update_password'
    end
  end 

  resources :users do
    resources :employees do
      collection do

        get "dashboard"
        get "send_email" 
        get    'employee_dashboard'
        get    'academic_detail_new'
        post   'academic_detail_create'
        get    'academic_detail_edit'
        patch  'academic_detail_update'
        get    'academic_detail_display'
        get    'basic_detail_new'
        post  'basic_detail_create'
        get    'basic_detail_show'
        get    'basic_detail_edit'
        patch  'basic_detail_update'
        get    'bank_detail_new'
        post   'bank_detail_create'
        get    'bank_detail_show'
        get    'bank_detail_edit'
        patch  'bank_detail_update'
        get    'previous_company_detail_new'
        get    'previous_company_detail_show'
        post   'previous_company_detail_create'
        get    'previous_company_detail_edit'
        patch  'previous_company_detail_update'
        get    'project_new'
        post   'project_create'
        get    'project_show'
        get    'project_edit'
        patch  'project_update'
       end

      end

      resources :sales_consultants do
        collection do
        get    'saleconsultant_new'
        post   'saleconsultant_create'
        get    'saleconsultant_edit'
        get    'saleconsultant_show'
        patch  'saleconsultant_update'
        get    'sales_bd_new'
        post   'sales_bd_create'
        get    'sales_bd_edit'
        get     'sales_bd_show'
        patch  'sales_bd_update'

      end
    end    
  end 
end

app/models/sales_consultant.rb
class SalesConsultant < ActiveRecord::Base
  belongs_to :user
  validates :name,:contact,:email_id,:bank_account_no,:ifsc_code,presence:true
	validates :comission,:allow_nil => true,:numericality => { :greater_than => 0.00 }
	validates :skype_id,:allow_nil => true, uniqueness: true
	validates :contact,length: {minimum:10 ,maximum: 10}
	validates :email_id,format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
	validates :bank_account_no,uniqueness: true , :numericality => true ,length: {minimum:6 ,maximum: 17}
	validates :ifsc_code,format: { with: /\A[a-zA-Z0-9]+\z/, message: "only allows 11 digits"},length: {minimum:11 ,maximum: 11}
end

app/controllers/sales_consultants_controller.rb
class SalesConsultantsController < ApplicationController
  
  def sales_bd_new
    @sale = current_user.sales_bds.new
  end

  def sales_bd_create
    @sale = current_user.sales_bds.create(sale_params)
    if @sale.save
      redirect_to sales_bd_show_user_sales_consultants_path(current_user), :notice => "Details saved."
    else
      render 'sales_bd_new'
    end
  end

  def sales_bd_show
    if current_user.sales_bds.blank?
      redirect_to  sales_bd_new_user_sales_consultants_path(current_user)
    else
      @sale = current_user.sales_bds
    end 
  end 

  def sales_bd_edit
    @sale = current_user.sales_bds.find(params[:sale])
  end

  def sales_bd_update
     @sale = current_user.sales_bds.find(params[:sale])
       if @sale.update_attributes(sale_params)
         redirect_to sales_bd_show_user_sales_consultants_path(current_user)
       else
         render 'sales_bd_edit'
      end
  end

 def saleconsultant_new
    @consultant = current_user.sales_consultants.new
 end

 def saleconsultant_create
    @consultant = current_user.sales_consultants.create(sales_params)
    if @consultant.save
      redirect_to saleconsultant_show_user_sales_consultants_path(current_user), :notice => "Details saved."
    else
      render "saleconsultant_new"
    end
 end

 def saleconsultant_edit
  @consultant = current_user.sales_consultants.find(params[:consultants])
 end

 def saleconsultant_show
   if current_user.sales_consultants.blank?
    redirect_to saleconsultant_new_user_sales_consultants_path(current_user)
  else
    @consultants = current_user.sales_consultants
  end
 end

 def saleconsultant_update
  @consultant = current_user.sales_consultants.find(params[:consultants])
  if @consultant.update_attributes(sales_params)
    redirect_to saleconsultant_show_user_sales_consultants_path(current_user)
  else
    render 'saleconsultant_new'
  end
end

private

def sales_params
  params.require(:sales_consultant).permit(:user_id, :name, :comission, :contact,:skype_id, :email_id,:location, :address,:bank_account_no,:bank_name,:ifsc_code)
end

def sale_params
  params.require(:sales_bd).permit(:sales_id, :skype_id)
end
end

app/helpers/sales_consultants_helper.rb
module SalesConsultantsHelper
end

app/views/sales_consultants/saleconsultant_edit.html.erb
<section id="main-content">
  <section class="panel">
   <div class="col-lg-12">
     <section class="panel padding">
        <header class="panel-heading bgcolor" >
          <bold><h4>Edit Consultant Details</h4></bold>
        </header>
        <%= form_for @consultant, :url =>  saleconsultant_update_user_sales_consultants_path(current_user, :consultants =>@consultant.id) do |f| %>
              <div class=" col-lg-3">
              </div>
              <div class="panel-body">
              <div class=" form">
                <% if  @consultant.errors.any? %>
                <div id="error_explanation" class ="alert alert-danger">
                  <ul>
                    <%  @consultant.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
                <% end %>
                <div class=" form col-lg-9">
                  <form class="cmxform form-horizontal tasi-form" id="commentForm" method="get" action="">
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Name* </label>
                      <div class="col-lg-8">
                        <%= f.text_field :name ,:class=>"form-control", :value => (current_user.firstname+" "+current_user.lastname if current_user.firstname.present? || f.object.new_record? ),:readonly => true %><br/>
                    
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Commission </label>
                      <div class="col-lg-8">
                        <%= f.text_field :comission,:class=>"form-control"%><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Contact* </label>
                      <div class="col-lg-8">
                        <%= f.text_field :contact ,:class=>"form-control", :required => true %><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Skype Id</label>
                      <div class="col-lg-8">
                        <%= f.text_field :skype_id,:class=>"form-control"%><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Email Id*</label>
                      <div class="col-lg-8">
                        <%= f.text_field :email_id ,:class=>"form-control",  :value => (current_user.email if current_user.email.present? || f.object.new_record? ),:readonly => true %><br/>
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Location</label>
                      <div class="col-lg-8">
                        <%= f.text_field :location ,:class=>"form-control" %><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Address </label>
                      <div class="col-lg-8">
                        <%= f.text_field :address,:class=>"form-control" %><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Bank Account No* </label>
                      <div class="col-lg-8">
                        <%= f.text_field :bank_account_no ,:class=>"form-control", :required => true %><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Bank Name </label>
                      <div class="col-lg-8">
                        <%= f.text_field :bank_name, :class=>"form-control"%><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> IFSC Code* </label>
                      <div class="col-lg-8">
                        <%= f.text_field :ifsc_code, :class=>"form-control", :required => true %><br />
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-lg-offset-3 col-lg-8">
                        <center><button class="btn btn-danger" type="submit">Save Changes</button>
                          <button class="btn btn-warning" type="back">Back</button>
                        </center>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            <% end %>
          </div>
        </section>
      </div>
  </section>
</section>

app/views/sales_consultants/saleconsultant_new.html.erb
<section id="main-content">
  <section class="panel">
   <div class="col-lg-12">
     <section class="panel padding">
        <header class="panel-heading bgcolor">
          <bold><h4>Consultant Details</h4></bold>
        </header>
        <%= form_for [current_user, current_user.sales_consultants.build], :url =>  saleconsultant_create_user_sales_consultants_path(current_user) do |f| %>
              <div class=" col-lg-3">
              </div>
              <div class="panel-body">
              <div class=" form">
                <% if  @consultant.errors.any? %>
                <div id="error_explanation" class ="alert alert-danger">
                  <ul>
                    <%  @consultant.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
                <% end %>
                <div class=" form col-lg-9">
                  <form class="cmxform form-horizontal tasi-form" id="commentForm" method="get" action="">
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Name* </label>
                      <div class="col-lg-8">
                        <%= f.text_field :name ,:class=>"form-control", :value => (current_user.firstname+" "+current_user.lastname if current_user.firstname.present? || f.object.new_record? ),:readonly => true %><br/>
                    
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Commission </label>
                      <div class="col-lg-8">
                        <%= f.text_field :comission,:class=>"form-control"%><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Contact* </label>
                      <div class="col-lg-8">
                        <%= f.text_field :contact ,:class=>"form-control", :required => true %><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Skype Id</label>
                      <div class="col-lg-8">
                        <%= f.text_field :skype_id,:class=>"form-control"%><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Email Id*</label>
                      <div class="col-lg-8">
                        <%= f.text_field :email_id ,:class=>"form-control",  :value => (current_user.email if current_user.email.present? || f.object.new_record? ),:readonly => true %><br/>
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Location</label>
                      <div class="col-lg-8">
                        <%= f.text_field :location ,:class=>"form-control" %><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Address </label>
                      <div class="col-lg-8">
                        <%= f.text_field :address,:class=>"form-control" %><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Bank Account No* </label>
                      <div class="col-lg-8">
                        <%= f.text_field :bank_account_no ,:class=>"form-control", :required => true %><br />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> Bank Name </label>
                      <div class="col-lg-8">
                        <%= f.text_field :bank_name, :class=>"form-control"%><br />
                      </div>
                    </div>
                   
                    <div class="form-group ">
                      <label class="col-lg-3 control-label"> IFSC Code* </label>
                      <div class="col-lg-8">
                        <%= f.text_field :ifsc_code, :class=>"form-control", :required => true %><br />
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-lg-offset-3 col-lg-8">
                        <center><button class="btn btn-danger" type="submit">Save Consultant Details</button>
                          <button class="btn btn-warning" type="reset">Reset</button>
                        </center>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
          <% end %>
        </div>
      </section>
    </div>
  </section>
</section>

app/views/sales_consultants/saleconsultant_show.html.erb
<section id="main-content">
    <section class="wrapper">
       <div class="row">
         <div class="col-lg-12">
            <section class="panel">
               <header class="panel-heading bgcolor">
                  <bold><h4>Consultant Details</h4></bold>
                </header>
                  <table class="table table-bordered table-striped table-hover table-condensed">
                   <thead>
                        <tr>
                          <th>Name</th>
                          <th>Commission</th>
                          <th>Contact</th>
                          <th>Skype Id</th>
                          <th>Email Id</th>
                          <th>Location</th>
                          <th>Address</th>
                          <th>Bank Account No</th>
                          <th>Bank Name</th>
                          
                          <th>IFSC Code</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @consultants.each do |consultant| %>
                          <tr>
                            <td><%= consultant.name.titleize %></td>
                            <td><%= consultant.comission%></td>
                            <td><%= consultant.contact%></td>
                            <td><%= consultant.skype_id%></td>
                            <td><%= consultant.email_id%></td>
                            <td><%= consultant.location.titleize%></td>
                            <td><%= consultant.address %></td>
                            <td><%= consultant.bank_account_no%></td>
                            <td><%= consultant.bank_name.titleize%></td>
                            <td><%= consultant.ifsc_code%></td>
                            <td><%= link_to "Edit",  saleconsultant_edit_user_sales_consultants_path(current_user, :consultants => consultant),class: "btn btn-primary btn-xs"  %></td>
                          </tr>
                        <% end %>
                      </tbody>
                  </table>
                  </section>
                  <%= link_to "Add More",  saleconsultant_new_user_sales_consultants_path(current_user),class: "btn btn-primary btn-xs" %>
          </div>
        </div>
    </section>
</section>
 

app/views/sales_consultants/sales_bd_edit.html.erb
<section id="main-content">
  <section class="panel">
   <div class="col-lg-12">
     <section class="panel padding">
        <header class="panel-heading bgcolor">
          <bold><h4>Edit BDE Details</h4></bold>
        </header>
          <%= form_for @sale, :url =>sales_bd_update_user_sales_consultants_path(current_user ,:sale => @sale.id) do |f| %>

              <div class="panel-body">
                 <div class=" form">
                   <% if @sale.errors.any? %>
                     <div id="error_explanation" class ="alert alert-danger">
                       <ul>
                        <% @sale.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                       </ul>
                    </div>
                   <% end %>
                      <div class="col-lg-9">
                         <form class="cmxform form-horizontal tasi-form" id="commentForm" method="get" action="">
                           <div class="form-group ">
                              <label class="col-lg-3 control-label"> Sales Id:* </label>
                                 <div class="col-lg-8">
                                    <%= f.text_field :sales_id, :class=>"form-control", :required => true %><br/>
                                  </div>
                           </div>

                           <div class="form-group ">
                            <label class="col-lg-3 control-label"> Skype Id:* </label>
                             <div class="col-lg-8">
                               <%= f.text_field :skype_id, :value => EmployeeDetail.skype_search(current_user) ,:class=>"form-control" %><br/>
                             </div>
                           </div>

                          <div class="form-group">
                            <div class="col-lg-offset-3 col-lg-8">
                              <center><button class="btn btn-danger" type="submit">Save Changes</button>
                              <button class="btn btn-warning" type="back">Back</button></center>
                            </div>
                          </div>
                     </div>
                  </form>
                </div>
              <% end %>
          </div>
        </div>
      </section>
    </div>
  </section>
</section>

app/views/sales_consultants/sales_bd_new.html.erb
<section id="main-content">
  <section class="panel">
   <div class="col-lg-12">
     <section class="panel padding">
        <header class="panel-heading bgcolor">
          <bold><h4>BDE Details</h4></bold>
        </header>
            <%= form_for [current_user, current_user.sales_bds.build], :url =>sales_bd_create_user_sales_consultants_path(current_user), :method => "post"  do |f| %>
                <div class="panel-body">
                  <div class=" form">
                    <% if @sale.errors.any? %>
                      <div id="error_explanation" class ="alert alert-danger">
                     <ul>
                       <% @sale.errors.full_messages.each do |message| %>
                       <li><%= message %></li>
                       <% end %>
                     </ul>
                   </div>
                  <% end %>
                  <div class="col-lg-9">
                    <form class="cmxform form-horizontal tasi-form" id="commentForm" method="get" action="">
                      <div class="form-group ">
                        <label class="col-lg-3 control-label"> Sales Id:* </label>
                        <div class="col-lg-8">
                          <%= f.text_field :sales_id, :class=>"form-control", :required => true %><br/>
                        </div>
                      </div>

                      <div class="form-group ">
                        <label class="col-lg-3 control-label"> Skype Id:* </label>
                         <div class="col-lg-8">
                           <%= f.text_field :skype_id, :value => EmployeeDetail.skype_search(current_user),    :class=>"form-control"%><br/>   
                         </div>
                      </div>

                      <div class="form-group">
                        <div class="col-lg-offset-3 col-lg-8">
                          <center><button class="btn btn-danger" type="submit">Save BDE Details</button></center>
                        </div>
                      </div>
                  </div>
                </form>
              </div>
            <% end %>
        </div>
      </div>
    </section>
  </div>
</section>
</section>

app/views/sales_consultants/sales_bd_show.html.erb
<section id="main-content">
    <section class="wrapper">
       <div class="row">
         <div class="col-lg-12">
            <section class="panel">
               <header class="panel-heading bgcolor">
                 <bold><h4>Sales BDE Details</h4></bold>
                </header>
                  <table class="table table-bordered table-striped table-hover table-condensed">
                   <thead>
                     <tr>
                       <th>Sales Id</th>
                       <th>Skype Id</th>
                       <th></th>
                     </tr>
                   </thead>
                   <tbody>
                    <% @sale.each do |sale| %>
                      <tr> 
                        <td><%= sale.sales_id %></td>
                        <td><%= sale.skype_id%></td>
                        <td><%= link_to "Edit", sales_bd_edit_user_sales_consultants_path(current_user, :sale => sale),class: "btn btn-primary btn-xs" %></td>
                      </tr>
                    <% end %>
                   </tbody>
                </table>
            </section>
            <%= link_to "Add More",  sales_bd_new_user_sales_consultants_path(current_user),class: "btn btn-primary btn-xs" %>
          </div>
        </div>
   </section>
</section>