config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations"}
  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end  
  get 'users/soft_delete' => 'users/soft_delete'
  root 'users#index'

  resource :user, only: [:edit] do
    collection do
      get 'edit_password'
      patch 'update_password'
    end
  end 

  resources :users do
    resources :employees do
      collection do

        get "dashboard"
        get "send_email" 
        get    'employee_dashboard'
        get    'academic_detail_new'
        post   'academic_detail_create'
        get    'academic_detail_edit'
        patch  'academic_detail_update'
        get    'academic_detail_display'
        get    'basic_detail_new'
        post  'basic_detail_create'
        get    'basic_detail_show'
        get    'basic_detail_edit'
        patch  'basic_detail_update'
        get    'bank_detail_new'
        post   'bank_detail_create'
        get    'bank_detail_show'
        get    'bank_detail_edit'
        patch  'bank_detail_update'
        get    'previous_company_detail_new'
        get    'previous_company_detail_show'
        post   'previous_company_detail_create'
        get    'previous_company_detail_edit'
        patch  'previous_company_detail_update'
        get    'project_new'
        post   'project_create'
        get    'project_show'
        get    'project_edit'
        patch  'project_update'
       end

      end

      resources :sales_consultants do
        collection do
        get    'saleconsultant_new'
        post   'saleconsultant_create'
        get    'saleconsultant_edit'
        get    'saleconsultant_show'
        patch  'saleconsultant_update'
        get    'sales_bd_new'
        post   'sales_bd_create'
        get    'sales_bd_edit'
        get     'sales_bd_show'
        patch  'sales_bd_update'

      end
    end    
  end 
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom custom-foot">
  <div class="text-center">
    copyright &copy; <%= Time.now.year %> Affimintus Technologies
    <a href="#" class="go-top">
       <i class="fa fa-angle-up"></i>
    </a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header white-bg">
 <!--logo start-->
  <a href="/" class="logo">Affi<span>MIS</span></a>
  <!--logo end-->
  <div class="nav notify-row" id="top_menu">
    <!--  notification start -->
    <ul class="nav top-menu">
      <!-- settings start -->
      <li class="dropdown">
        <!-- <a data-toggle="dropdown" class="dropdown-toggle" href="#">
        <i class="fa fa-tasks"></i>
        <span class="badge bg-success">6</span>
        </a> -->
        <ul class="dropdown-menu extended tasks-bar">
          <div class="notify-arrow notify-arrow-green"></div>
          <li>
            <p class="green">You have 6 pending tasks</p>
          </li>
          <li>
            <a href="#">
              <div class="task-info">
                <div class="desc">Dashboard v1.3</div>
                <div class="percent">40%</div>
              </div>
              <div class="progress progress-striped">
                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                  <span class="sr-only">40% Complete (success)</span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="task-info">
                <div class="desc">Database Update</div>
                <div class="percent">60%</div>
              </div>
              <div class="progress progress-striped">
                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                  <span class="sr-only">60% Complete (warning)</span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="task-info">
                <div class="desc">Iphone Development</div>
                <div class="percent">87%</div>
              </div>
              <div class="progress progress-striped">
                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 87%">
                  <span class="sr-only">87% Complete</span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="task-info">
                <div class="desc">Mobile App</div>
                <div class="percent">33%</div>
              </div>
              <div class="progress progress-striped">
                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 33%">
                  <span class="sr-only">33% Complete (danger)</span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="task-info">
                <div class="desc">Dashboard v1.3</div>
                <div class="percent">45%</div>
              </div>
              <div class="progress progress-striped active">
                <div class="progress-bar"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
                  <span class="sr-only">45% Complete</span>
                </div>
              </div>
            </a>
          </li>
          <li class="external">
            <a href="#">See All Tasks</a>
          </li>
        </ul>
      </li>
      <!-- settings end -->
      <!-- inbox dropdown start-->
      <%# if current_user.role != "Client"%>
        <li id="header_inbox_bar" class="dropdown">
         <a data-toggle="dropdown" class="dropdown-toggle" href="#" title="List of pending leaves.">
          <i class="fa fa-envelope-o"></i>
            <span class="badge bg-important">
               <%# if current_user.role == "admin" || current_user.role == "Hr" || current_user.role == "Teamlead"%>
                 <%#= pending_leave_count %>
               <%# else %>
                 <%#= employee_pending_leave_count%>
               <%# end %>
            </span>
         </a>
          <ul class="dropdown-menu extended inbox">
            <div class="notify-arrow notify-arrow-red"></div>
            <li>
                <%# if current_user.role == "admin" || current_user.role == "Hr" || current_user.role == "Teamlead"%>
                  <p class="red">You have <%#= pending_leave_count %> pending leaves.</p>
                <%# else %>
                   <p class="red">You have <%#= employee_pending_leave_count%> new message</p>
                <%# end %>
            </li>
              <div style=" height: 350px; overflow: auto;">
                <%# if current_user.role == "admin" || current_user.role == "Hr" || current_user.role == "Teamlead" %>
                    <%# if @pending_leaves.present? %>
                       <%# @pending_leaves.each do |holiday| %>
                       <li>
                         <tr>
                           <td><i class="fa fa-envelope-o"></i>&nbsp;<strong>Leave for</strong>:-<%#= link_to user_holiday_path( current_user,holiday) do %>
                            <b><%#= User.where(:id => holiday.user_id).last.first_name.capitalize rescue nil%></b>
                             <%#=holiday.leave_to_date%>&nbsp;to&nbsp;<%#=holiday.leave_from_date%>
                             <%#end%>
                             <%#= current_user.first_name.capitalize rescue nil%>
                           </td>                  
                         </tr>
                       </li>
                     <%# end %>
                   <% #end %>
                 <%# elsif %>
                  <%# if @employee_pending_leaves.present? %>
                    <%# @employee_pending_leaves.each do |holiday| %>
                      <li>
                        <tr>
                           <td><i class="fa fa-envelope-o"></i>&nbsp;Leave for<%#= link_to user_holiday_path( current_user,holiday) do %>
                            <b><%#= User.where(:id => holiday.user_id).last.first_name.capitalize%></b>
                            <%#=holiday.leave_to_date%>&nbsp;to&nbsp;<%#=holiday.leave_from_date%>
                            <%#end%>
                          </td>                  
                        </tr>
                      </li>
                    <%# end %>
                  <%# end %>
                <%# elsif %>
                  <!-- <strong>NO RECENT LEAVE !</strong> -->
                <%# end %>
            </div>
        </li>
      </ul>  
   </li>
<%# end %>
        
      <!-- inbox dropdown end -->
      <!-- notification dropdown start-->
      <li id="header_notification_bar" class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#" title="List of notifications.">
        <i class="fa fa-bell-o"></i>
        <span class="badge bg-success">
          <%#= unread_notifications_count %>
        </span>
        </a>
        <ul class="dropdown-menu extended notification">
          <div class="notify-arrow notify-arrow-yellow"></div>
          <li>
            <p class="yellow">You have <%#= unread_notifications_count %> new notifications</p>
          </li>
          <div  style=" height: 250px; overflow: auto;">
          <li>  
            <%# if @unread_notifications.present? %>
              <%# @unread_notifications.each do |notification| %>
                <li>
                  <tr>
                  <td><i class="fa fa-bell"></i><%#= link_to notification.title, user_notification_path(current_user, notification) %></td>
                  <td><%#= notification.description %></td>
                  <!-- <td><%#= link_to 'Display Notification', user_notification_path(current_user, notification) %></td> -->
                  </tr>
                </li>
              <%# end %>
            <%# else %>
              <strong>NO RECENT NOTIFICATIONS !</strong>  
            <%# end %>
          </li>
          </div>
          <li>
            <%#= link_to user_notifications_path(current_user) do %>
              <i class="fa fa-bell"></i>
              <span>See all notifications</span>
            <%# end %>
          </li>
        </ul>
      </li>
      <!-- notification dropdown end -->
    </ul>
    <!--  notification end -->
  </div>
  <div class="top-nav ">
    <!--search & user info start-->
    <ul class="nav pull-right top-menu">
      
      <!-- user login dropdown start-->
      <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
          <!-- <img alt="" src="img/avatar1_small.jpg"> -->
          <%# if user_signed_in? %>
           <%# if current_user.role == "admin"||current_user.role == "Client"%>
              <!-- <img src="/assets/2.jpg", style="width: 50px;"> -->
           <%#else%>
              <%#= image_tag current_user.employee_detail.avatar_url, :size =>"40x40" if current_user.employee_detail.present?  rescue''%>
           <%#end%>
           
            <span class="username"><%= current_user.email.capitalize if current_user.email.present? %></span>
          <%# end %>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu extended logout">
          <div class="log-arrow-up"></div>
          <%# if current_user.role == "admin"%>
          <li>
          <%#= link_to '<i class=" fa fa-suitcase"></i>Profile'.html_safe, users_path(current_user) %>
          </li>
          <%# elsif current_user.role == "Client"%>
          <li>
          <%#= link_to '<i class=" fa fa-suitcase"></i>Profile'.html_safe, client_basic_detail_display_user_sales_path(current_user)%>
          </li>
          <% else %>
          <li>
          <%#= link_to '<i class=" fa fa-suitcase"></i>Profile'.html_safe, user_employee_path(current_user, current_user)%>
          </li>
          <%# end %>
          <li>
            <%= link_to '<i class="fa fa-sign-out "></i> Logout'.html_safe, destroy_user_session_path, :method => :delete %>
          </li>
        </ul>
      </li>
      <!-- user login dropdown end -->
    </ul>
    <!--search & user info end-->
  </div>
</header>

app/views/layouts/_message.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" style="margin-top: 1%; color: #2A3542; text-align: center; font-size: 15px;">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :p, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_sidebar.html.erb
<br><br>
<aside>
  <div id="sidebar"  class="nav-collapse" style="overflow: hidden;" tabindex="5000">
  <!-- sidebar menu start-->
  <ul class="sidebar-menu" id="nav-accordion">
    <li class="sub-menu">
      <li>
      <!-- ********************* dashboard ****************** -->
        <% subtabs_path = [users_path] %>
        <a class="<%= is_active?(subtabs_path) %>" href="/users">

        <i class="fa fa-dashboard"></i>
        <span>Dashboard</span>
        </a>
        </li>
        <!-- ********************* if admin ****************** -->
        <% if current_user.has_role? "admin" %>
        <li>
        <% if params[:action] != "new" %>
          <% subtabs_path1 = [new_user_registration_path] %>
          <li><%= link_to '<i class="fa fa-users "></i> Create User'.html_safe, new_user_registration_path, class: "#{ is_active?(subtabs_path1)}"%></li>
        <% else %>
          <% subtabs_path2 = [users_path] %>
          <li><%= link_to '<i class="fa fa-chevron-circle-left"></i> Back'.html_safe, users_path, class: "#{ is_active?(subtabs_path2) }" %></li>
        <% end %> 
        </li>
        <%end%>
      <!-- ********************* if admin close ****************** -->          
      </li>
    </li>
  </ul>
      <div id="sidebar"  class="nav-collapse" style="overflow: hidden;" tabindex="5000">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">
          <li class="sub-menu">
          <li><li>
          <!-- ********************* dashboard ****************** -->
              

              <i class="fa fa-dashboard"></i>
              <span>Dashboard</span>
              </a>
          </li>
          
         

          <li><% if current_user.has_role? :Employee %>
          <span>My Account</span> </li>
            
              <ul class="sub">
                <li><%=link_to "Basic Details",  basic_detail_show_user_employees_path(current_user)%></li>
                <li><%=link_to "Academic Details", academic_detail_display_user_employees_path(current_user) %></li>
                <li><%=link_to "Bank Identity Details",  bank_detail_show_user_employees_path(current_user) %></li>
                <li><%= link_to "Previous Company Details", previous_company_detail_show_user_employees_path(current_user) %></li>
                <li><%= link_to "<i class='glyphicon glyphicon-wrench'></i> Project Details".html_safe, project_show_user_employees_path(current_user)%></li>
             
             </ul>
           <% end %>

            <li><% if current_user.has_role? :sale_consultant %>

                
                <li><%=link_to "Basic Details",  basic_detail_show_user_employees_path(current_user)%></li>
                <li><%=link_to "Academic Details", academic_detail_display_user_employees_path(current_user) %></li>
                <li><%=link_to "Bank Identity Details",  bank_detail_show_user_employees_path(current_user) %></li>
                <li><%= link_to "Previous Company Details", previous_company_detail_show_user_employees_path(current_user) %></li>
                <li><%= link_to "<i class='glyphicon glyphicon-wrench'></i> Project Details".html_safe, project_show_user_employees_path(current_user)%></li>
             
             
                  <li><%=link_to "sale consultant Details",  saleconsultant_show_user_sales_consultants_path(current_user)%></li>

                 <li> <%=link_to "sale BD Details",  sales_bd_show_user_sales_consultants_path(current_user)%></li>
                  <%end %>

    </aside>
    <script type="text/javascript">
      $('li#my-acc > a').on( "click", function() {
        $('li#my-acc > a').toggleClass('active');
        $('li#my-acc').toggleClass('active');
      });
      $('li#my-proj > a').on( "click", function() {
        $('li#my-proj > a').toggleClass('active');
        $('li#my-proj').toggleClass('active');
      });
      $('li#notification > a').on( "click", function() {
        $('li#notification > a').toggleClass('active');
        $('li#notification').toggleClass('active');
      });
      $('li#notification1 > a').on( "click", function() {
        $('li#notification1 > a').toggleClass('active');
        $('li#notification1').toggleClass('active');
      });
      $('li#my-leave > a').on( "click", function() {
        $('li#my-leave > a').toggleClass('active');
        $('li#my-leave').toggleClass('active');
      });
      $('li#my-invoice > a').on( "click", function() {
        $('li#my-invoice > a').toggleClass('active');
        $('li#my-invoice').toggleClass('active');
      });
      $('li#client-details > a').on( "click", function() {
        $('li#client-details > a').toggleClass('active');
        $('li#client-details').toggleClass('active');
      });
      $('li#my-feedback > a').on( "click", function() {
        $('li#my-feedback > a').toggleClass('active');
        $('li#my-feedback').toggleClass('active');
      });
      $('li#my-attendance > a').on( "click", function() {
        $('li#my-attendance > a').toggleClass('active');
        $('li#my-attendance').toggleClass('active');
      });
      $('li#my-task > a').on( "click", function() {
        $('li#my-task > a').toggleClass('active');
        $('li#my-task').toggleClass('active');
      });
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Mosaddek">
  <meta name="keyword" content="Affi, Affimintus, affimintus, mis, affi-mis">
  <title>Affi MIS</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css' %>
  <%= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.6.1/fullcalendar.min.css' %>
   <%#= wicked_pdf_stylesheet_link_tag "pdf" -%>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.min.js' %>
  <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.6.1/fullcalendar.min.js' %>
  <%#= javascript_include_tag "application", "rails.validations"%>
  <%= csrf_meta_tags %>
</head>
<body>
 <section id="container" >
    <%  if user_signed_in? %>
      <%= render :partial => 'layouts/header' %>
      <%= render :partial => 'layouts/sidebar' %>
    <% end %>
      <%= render 'layouts/message' %>
    <%= yield %>
    <%= render :partial => 'layouts/footer' %>
  </section>
</body>
</html>